name: 🚀 Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_DEPLOY_KEY }}
    
      - name: Deploy to Droplet
        run: |
          ssh-keyscan -H ${{ secrets.DIGITALOCEAN_DROPLET_HOST }} >> ~/.ssh/known_hosts
          ssh -T ${{ secrets.DIGITALOCEAN_DROPLET_USER }}@${{ secrets.DIGITALOCEAN_DROPLET_HOST }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ${{ vars.DIGITALOCEAN_APP_DIR }}
            echo "🔄 Pulling latest changes..."
            git pull origin master
            echo "📦 Installing dependencies..."
            npm install
            echo "🔨 Building app..."
            npm run build
            echo "🚀 Restarting app"
            pm2 restart ${{ vars.DIGITALOCEAN_PM2_NAME }}
            echo "✅ Deployment complete!"
          EOF